---
title: "Assignment 4"
subtitle: "Marks and Channels"
author: "Robyn Steveley"
date: "2024-02-11"
categories: [assignment]

code-fold: true
code-tools: true
description: "In progress..."
---

# Marks and Channels

```{r}
#| output: false
library(tidyverse)
```

The Data sets being used:

[Top 100 Young Adult Books](https://data.world/yansian/top-100-young-adult-fiction)

```{r}
BOOKS <- read.csv("goodreads_Top100_YoungAdultFiction1.csv")
```

## Expressiveness and Effectiveness

Figure 1

```{r}

```

Figure 2

```{r}

```

## Discriminability

```{r}
#fig 3
fig_3 <- ggplot(BOOKS, aes(pages))+ geom_histogram(binwidth = 20, color="blue", fill="blue")

fig_3_titles <- labs(title = "Number of Pages for Top 100 Young Adult Books", 
                     caption = "This graph shows the number of pages of the most popular young adult books to within 20 pages.")
fig_3_theme <- theme(panel.background=element_rect(fill="white"), 
                     plot.caption = element_text(hjust = 0.5))

fig_3 <- fig_3 + fig_3_titles + fig_3_theme

print(fig_3)

```

```{r}
#fig 4
fig_4 <- ggplot(BOOKS, aes(pages))+ geom_histogram(binwidth = .5, color="red", fill="red")

fig_4_titles <- labs(title = "Number of Pages for Top 100 Young Adults Books",
              caption = "This uses bin sizes of half a page. The data doesn't even measure book length to half pages.")
fig_4_theme <- theme(panel.background=element_rect(fill="white"),
                     plot.caption = element_text(hjust = 0.5))

fig_4 <- fig_4 + fig_4_titles + fig_4_theme

print(fig_4)
```

## Separability

Figure 5

```{r}

```

Figure 6

```{r}

```

## Popout

Figure 7

```{r}

```

Figure 8

```{r}

```
